menu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.menu_view, name='index'),
    path('menu/<int:pk>/edit/', views.menu_detail, name='edit'),
    path('menu/new/', views.create_new_menu, name='create_new_menu'),
    path('menu/<int:pk>/delete/', views.delete_menu, name='delete'),
    path('menu/add/ingredient/', views.add_ingredient, name='add_ingredient'),
    path('menu/add/item/', views.add_item, name='add_item'),
]

project_9_improve_django/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar

urlpatterns = [
    path('', include('menu.urls', namespace='menu')),
    path('admin/', admin.site.urls),
    path(r'__debug__', include(debug_toolbar.urls))
]

menu/models.py
from django.db import models
from django.utils import timezone

class Menu(models.Model):
    season = models.CharField(max_length=20)
    created_date = models.DateTimeField(default=timezone.now)
    expiration_date = models.DateTimeField()
    items = models.ManyToManyField('Item')

    def __str__(self):
        return self.season


class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    standard = models.BooleanField(default=False)
    ingredients = models.ManyToManyField('Ingredient')

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

menu/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget

from . import models

class MenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ['season', 'expiration_date', 'items']
        widgets = {
            'expiration_date': SelectDateWidget()
        }


class IngredientForm(forms.ModelForm):
    class Meta:
        model = models.Ingredient
        fields = ['name']


class ItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = ['name', 'description', 'standard', 'ingredients']

menu/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from . import models
from . import forms

def menu_view(request):
    menus = models.Menu.objects.all()
    return render(request, 'menu_list.html', {'menus': menus})


def menu_detail(request, pk):
    instance = models.Menu.objects.get(pk=pk)
    items = models.Item.objects.all()
    form = forms.MenuForm(instance=instance)
    if request.method == 'POST':
        form = forms.MenuForm(request.POST, instance=instance)
        if form.is_valid():
            # don't understand this line completely
            # many to many
            instance.items.set(request.POST.get('items', ''))
            instance.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Your menu has been succesfully updated!")
            return HttpResponseRedirect(reverse('menu:index'))
    return render(request, 'menu_detail.html', {'form': form})


def create_new_menu(request):
    form = forms.MenuForm()
    if request.method == 'POST':
        form = forms.MenuForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Your menu has been succesfully created!")
            return HttpResponseRedirect(reverse('menu:index'))
    return render(request, 'menu_detail.html', {'form': form})


def delete_menu(request, pk):
    menu = models.Menu.objects.get(pk=pk)
    menu.delete()
    messages.add_message(
        request,
        messages.SUCCESS,
        "Menu has been sucessfully deleted!")
    return HttpResponseRedirect(reverse('menu:index'))


def add_ingredient(request):
    form = forms.IngredientForm()
    if request.method == 'POST':
        form = forms.IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Ingredient has been succesfully added!")
            return HttpResponseRedirect(reverse('menu:index'))
    return render(request, 'menu_detail.html', {'form': form})


def add_item(request):
    form = forms.ItemForm()
    if request.method == 'POST':
        form = forms.ItemForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Item has been succesfully added!")
            return HttpResponseRedirect(reverse('menu:index'))
    return render(request, 'menu_detail.html', {'form': form})

menu/templates/menu/layout.html
<html>
    <head>
        <title>Soda Fointain</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row justify-content-center mt-3">
                <a href="{% url 'menu:index' %}"><h1>Soda Fointain</h1></a>
            </div>
            <div class="row justify-content-center mb-2">
                {% if user.is_authenticated %}
                    <a class="btn btn-primary m-2" href="{% url 'menu:create_new_menu' %}" role="button">Add menu</a>
                    <a class="btn btn-primary m-2" href="{% url 'menu:add_ingredient' %}" role="button">Add ingredient</a>
                    <a class="btn btn-primary m-2" href="{% url 'menu:add_item' %}" role="button">Add item</a>
                {% else %}
                    <p>Please log in to add menu, ingredient or item</p>
                {% endif %}
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible justify-content-center" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <hr class="p-2"/>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

menu/templates/menu/menu_detail.html
{% extends "menu/layout.html" %}

{% block content %}

<div class="row justify-content-center">
  <form method="POST" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}

      <input type="submit" class="button-primary" value="Submit">
  </form>
</div>

{% endblock %}

menu/templates/menu/menu_list.html
{% extends "menu/layout.html" %}

{% block content %}

<div class="row">
    {% for menu in menus %}
        <div class="col-6">
            <div class="jumbotron">
              <h3><u>{{ menu.season }}</u></h3><br />
              {% for item in menu.items.all %}
                  <h6>{{ item }}</h6>
                  <h8>{{ item.description }}</h8><br />
                  {% for ingredient in item.ingredients.all %}
                    <ul>
                        <li>{{ ingredient }}</li>
                    </ul>
                  {% endfor %}
              <hr class="my-4">
              {% endfor %}
              <div class="row">
                  <div class='col'>
                      <a class="btn btn-info btn-lg" href="{% url 'menu:edit' pk=menu.pk %}" role="button">EDIT</a>
                  </div>
                  <div class='col'>
                      <a class="btn btn-danger btn-lg float-right" href="{% url 'menu:delete' pk=menu.pk %}" role="button">DELETE</a>
                  </div>
              </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}